pipeline:
  helm-package:
    image: alpine/helm:2.14.3
    commands:
      - helm init --client-only
      - helm package ./helm/nginx/ -d ./docs/
      - helm repo index ./docs/
    when:
      event: push
      #event: pull_request
      branch:
        exclude: master

# we are going to enter a loop here, if we commit to the same branch with the new packaged helm chart then drone is going to run this step again - would event: pull_request work?
# secrets are not exposed to PRs by default and if using secrets with PRs, the repo will need to be protected in drone
  git-push-helm:
    image: alpine/git:1.0.7
    secrets:
      - GIT_USER
      - GIT_PWD
      - GIT_EMAIL
    commands:
      - cd ./docs/
      - git init
      - git config --global user.email $$GIT_EMAIL
      - git remote set-url origin https://github.com/rhysemmas/helm-chart-hoster.git
      - git fetch
      - git pull
      - git status
      - git add .
      - git commit -m "Helm package robot commit"
      - git push https://$$GIT_USER:$$GIT_PWD@github.com/rhysemmas/helm-chart-hoster.git
    when:
      event: push
#      event: pull_request
      branch:
        exclude: master
