pipeline:
  helm-package:
    image: alpine/helm:2.14.3
    commands:
      - helm init --client-only
      - mkdir ./output/
      - helm package ./helm/nginx/ -d ./output/
      - helm repo index ./output/
    when:
      event: push

  git-push-helm:
    image: alpine/git:1.0.7
    secrets:
      - GIT_USER
      - GIT_PWD
      - GIT_EMAIL
    commands:
      - mkdir ./new-repo/ && cd ./new-repo/
      - git init
      - git config --global user.email $$GIT_EMAIL
      - git remote add origin https://$$GIT_USER:$$GIT_PWD@github.com/rhysemmas/helm-chart-hoster.git
      - git fetch
      - git checkout --track origin/master
      - git pull
      - mv ../output/* .
      - git add .
      - git commit -m "Helm package robot commit"
      - git push -u origin master
    when:
      event: push
