pipeline:
  helm-package:
    image: alpine/helm:2.14.3
    environment:
      APP: nginx
    secrets:
      - GIT_USER
      - GIT_TOKEN
      - GIT_EMAIL
    commands:
      sh ci/helm-package.sh
    when:
      event: push
