pipeline:
  helm-package:
    image: alpine/helm:2.14.3
    environment:
      APP: nginx
      REPO: github.com/rhysemmas/helm-chart-hoster.git
    secrets:
      - GIT_USER
      - GIT_TOKEN
      - GIT_EMAIL
    commands:
      sh ci/helm-package.sh
    when:
      event: push
